### ISSUE TITLE
Include all types in the output file

### ISSUE THREAD

**Issue by piuccio** [swansontec/rollup-plugin-flow-entry#5]
Hi, I've been using this project for a while but I've got a problem with nested modules, here's my setup:

### projectA

```js
export default function (a: TypeA) {}

export type TypeA = {};
```

this project A uses `rollup-plugin-flow-entry` and `rollup-plugin-flow`, so the output is

* `build/index.js` -> file without types
* `build/index.flow.js` -> file that imports types from `src/index.js`

### projectB

```js
import projA from 'projectA';
import type { TypeA } from 'projectA';

export default function (value: TypeA) { 
  projA(value);
}
```

this second project also uses `rollup-plugin-flow-entry` and `rollup-plugin-flow` but keeps `projectA` as dev dependency, because it's bundled by rollup in the final output file

The output is

* `build/index.js` -> merge `build/index.js` from projectA and `src/index.js` through rollup
* `build/index.flow.js` -> import types from `src/index.js`

## The problem

The problem now is that `index.flow.js` from projectB depends on the source files which in turns depend on the source files of projectA.

The best approach to minimize bundle size is to keep projectA as dev dependency, but that breaks flow checks because anyone using `projectB` does not have the types from `projectA`

The approach to make flow types work is to include `projectA` as a direct dependency of `projectB`, that way npm will be able to resolve the files and find the type definitions, but the drawback is that users of `projectB` will have one more dependency to download and many people already complain that the dependency tree of node modules is already too big.

## Question

Is there a way to use this plugin, or maybe another one, to actually copy the types into the bundle output?

Do you see any other approach that would work?

**Comment by swansontec** [comment]
I believe this is a fundamental limitation of the Flow language. You need all the source code to infer the types, which means you need to keep the whole dependency graph inside node_modules.

Typescript, in contrast, has a way to extract just the types into `.d.ts` files. If Flow had this, maybe you could bundle your dependency's types into your own type definitions. It looks like the Flow developers started down this road with the `gen-flow-files` command, but they never got it working correctly.

Given this, I think using `dependencies` is the best we can do for now.

This actually isn't so bad. When I write libraries, I usually only bundle my own code, not my dependencies. This way, if two libraries (A and B) happen to use a third dependency (C), my users don't end up with two copies of C, one each from A and B. I do this by setting rollup's `exclude` option to `Object.keys(packageJson.dependencies)`.

This kills two birds with one stone, since not only does it let my users de-duplicate their dependency tree, it means all the Flow types will be available in node_modules as part of that very same tree.

**Comment by piuccio** [comment]
Thanks for your answer, I'll go for `dependencies`, great clarification
